addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 32a57589-3123-43f6-aca6-b0815a213279
after_success:
- ./df-build.sh
jdk:
- oraclejdk8
language: java
notifications: {}
script: mvn test -Djacoco.skip=true
sudo: 'false'
# Modified by Insights Service at 2016-05-07 20:03:54.486717
