addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 96c0b417-e94f-4919-ab33-3cc1c39ea3e2
after_success:
- ./df-build.sh
jdk:
- oraclejdk8
language: java
notifications: {}
script: mvn clean install -DskipTests=true -Djacoco.skip=true -Dcobertura.skip=true
  -Dmaven.clover.skip=true
sudo: 'false'
# Modified by Insights Service at 2016-05-12 14:42:55.470352
